In [1]:
"""
Text Analytics
1. Extract Sample document and apply following document preprocessing methods:
Tokenization, POS Tagging, stop words removal, Stemming and Lemmatization.
2. Create representation of document by calculating Term Frequency and Inverse Document
Frequency.
"""

'\nText Analytics\n1. Extract Sample document and apply following document preprocessing methods:\nTokenization, POS Tagging, stop words removal, Stemming and Lemmatization.\n2. Create representation of document by calculating Term Frequency and Inverse Document\nFrequency.\n'

In [2]:
%pip install nltk --break-system-packages

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk) (8.1.6)
Requirement already satisfied: joblib in ./.local/lib/python3.12/site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 1.7 MB/s eta 0:00:00
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 6.8 MB/s eta 0:00:00
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 8.0 MB/s eta 0:00:0000:01m00:01
Downloading regex-2026.5.9-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.2/801.2 kB 7.6 MB/s eta 0:00:0000:0100:01
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 7.4 MB/s eta 0:00:00
Installing collected packages: tqdm, regex, nltk
  WARNING: The script tqdm is installed in '/home/pratiklimbekar/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk is installed in '/home/pratiklimbekar/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed nltk-3.9.4 regex-2026.5.9 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

In [17]:
import nltk
import pandas as pd
import numpy as np

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag

In [19]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to
[nltk_data]     /home/pratiklimbekar/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/pratiklimbekar/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/pratiklimbekar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/pratiklimbekar/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/pratiklimbekar/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/pratiklimbekar/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [7]:
sample = """
To be or not to be, that is the question. whether it is nobler for the mind to
suffer the slings and arrows of outrageous fortunes, or to take arms against a sea
of troubles and by opposing, end them. To die, to sleep, perchance have a dream!
Aye, there's the rub!
"""

In [11]:
#tokenization
tokens = word_tokenize(sample)
tokens

['To',
 'be',
 'or',
 'not',
 'to',
 'be',
 ',',
 'that',
 'is',
 'the',
 'question',
 '.',
 'whether',
 'it',
 'is',
 'nobler',
 'for',
 'the',
 'mind',
 'to',
 'suffer',
 'the',
 'slings',
 'and',
 'arrows',
 'of',
 'outrageous',
 'fortunes',
 ',',
 'or',
 'to',
 'take',
 'arms',
 'against',
 'a',
 'sea',
 'of',
 'troubles',
 'and',
 'by',
 'opposing',
 ',',
 'end',
 'them',
 '.',
 'To',
 'die',
 ',',
 'to',
 'sleep',
 ',',
 'perchance',
 'have',
 'a',
 'dream',
 '!',
 'Aye',
 ',',
 'there',
 "'s",
 'the',
 'rub',
 '!']

In [13]:
#Stop Words
stop_words = set(stopwords.words('english'))
filtered = [w for w in tokens if w.lower() not in stop_words and w.isalpha()]
filtered

['question',
 'whether',
 'nobler',
 'mind',
 'suffer',
 'slings',
 'arrows',
 'outrageous',
 'fortunes',
 'take',
 'arms',
 'sea',
 'troubles',
 'opposing',
 'end',
 'die',
 'sleep',
 'perchance',
 'dream',
 'Aye',
 'rub']

In [15]:
#Stemming
stemmer = PorterStemmer()
stemmed = [stemmer.stem(word) for word in filtered]
stemmed

['question',
 'whether',
 'nobler',
 'mind',
 'suffer',
 'sling',
 'arrow',
 'outrag',
 'fortun',
 'take',
 'arm',
 'sea',
 'troubl',
 'oppos',
 'end',
 'die',
 'sleep',
 'perchanc',
 'dream',
 'aye',
 'rub']

In [16]:
#Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized = [lemmatizer.lemmatize(word) for word in filtered]
lemmatized

['question',
 'whether',
 'nobler',
 'mind',
 'suffer',
 'sling',
 'arrow',
 'outrageous',
 'fortune',
 'take',
 'arm',
 'sea',
 'trouble',
 'opposing',
 'end',
 'die',
 'sleep',
 'perchance',
 'dream',
 'Aye',
 'rub']

In [20]:
#POS Tagging
pos = pos_tag(filtered)
pos

[('question', 'NN'),
 ('whether', 'IN'),
 ('nobler', 'NN'),
 ('mind', 'NN'),
 ('suffer', 'VBP'),
 ('slings', 'NNS'),
 ('arrows', 'VBZ'),
 ('outrageous', 'JJ'),
 ('fortunes', 'NNS'),
 ('take', 'VBP'),
 ('arms', 'NNS'),
 ('sea', 'NN'),
 ('troubles', 'NNS'),
 ('opposing', 'VBG'),
 ('end', 'NN'),
 ('die', 'NN'),
 ('sleep', 'JJ'),
 ('perchance', 'NN'),
 ('dream', 'NN'),
 ('Aye', 'NNP'),
 ('rub', 'NN')]

In [23]:
#Term frequency
from sklearn.feature_extraction.text import CountVectorizer

sample2 = ["To be or not to be, that is the question.", 
           "whether it is nobler for the mind to suffer the slings and arrows of outrageous fortunes", 
           "or to take arms against a sea of troubles and by opposing, end them.", 
           "To die, to sleep, perchance have a dream!", "Aye, there's the rub!"]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sample2)

tf = pd.DataFrame(X.toarray(), columns = vectorizer.get_feature_names_out())

tf

,against,and,arms,arrows,aye,be,by,die,dream,end,...,slings,suffer,take,that,the,them,there,to,troubles,whether
0,0,0,0,0,0,2,0,0,0,0,...,0,0,0,1,1,0,0,2,0,0
1,0,1,0,1,0,0,0,0,0,0,...,1,1,0,0,2,0,0,1,0,1
2,1,1,1,0,0,0,1,0,0,1,...,0,0,1,0,0,1,0,1,1,0
3,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,2,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0

In [24]:
#Inverse Document Frequency = importance of words
#common words have low val, rare ones have high
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(sample2)

idf = pd.DataFrame(
    X_tfidf.toarray(),
    columns = tfidf.get_feature_names_out()
)

idf

,against,and,arms,arrows,aye,be,by,die,dream,end,...,slings,suffer,take,that,the,them,there,to,troubles,whether
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.631826,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.315913,0.211571,0.000000,0.000000,0.355960,0.000000,0.000000
1,0.000000,0.215132,0.000000,0.266651,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.266651,0.266651,0.000000,0.000000,0.357158,0.000000,0.000000,0.150226,0.000000,0.266651
2,0.297876,0.240324,0.297876,0.000000,0.000000,0.000000,0.297876,0.000000,0.000000,0.297876,...,0.000000,0.000000,0.297876,0.000000,0.000000,0.297876,0.000000,0.167818,0.297876,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.399374,0.399374,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.450001,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.538498,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.360638,0.000000,0.538498,0.000000,0.000000,0.000000

In [ ]:
"""
TF = no of term occuring / total terms in doc
IDF = log(total docs/no of docs with the word)
"""